kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    env: development
    class: pod
  annotations:
    description: This is to show how labels work
spec:
  containers:
    - name: C01
      image: nginx
      command: ["/bin/bash","-c","while true; do echo Shubham Chiplunkar; sleep 5; done"]
  nodeSelector:
    hardware: t2.medium   # label the node first before applying this command, kubectl label node minikube hardware=t2.medium