kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  annotations:
    description: This is an deployment object
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: testpod
      labels:
        name: deployment
    spec:
      containers:
        - name: c00
          image: httpd
          port:
  	    containerPort: 80