kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    name: Shubham
  template:
    metadata:
      name: mypod
      labels:
	name: Shubham
    spec:
      containers:
        - name: C00
	  image: ubuntu
	  command: ["/bin/bash","-c","while true; do echo Shubham; sleep 5; done"]

