kind: Deployment
apiVersion: apps/v1
metadata:
  name:  pvdeploy
spec:
  replicas: 1
  selector: 
    app: mypv
  template:
    metadata:
      labels:
        app: mypv
    spec:
      container:
        - name: c00
  	  image: centos
 	  command: ["/bin/bash","-c","sleep 15000"]
	  volumeMounts:
   	    - name: mypd
	      mountPath: /tmp/persistent
      volumes:
        - name: mypd
	  persistentVolumeClaim:
	    claimName: myebsvolclaim
	  
