# kubectl create secret generic mysecret --from-file=username.txt --from-file=password.txt

apiVersion: v1
kind: Pod
metadata:
  name: myvolconfig
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/bash","-c","sleep 1500"]
      env:
        - name: USERNAME
	  valueFrom:
	    secretKeyRef:
	      name: mysecret
	      key: username.txt
	- name: PASSWORD
	  valueFrom:
  	    secretKeyRef:
  	      name: mysecret
              key: password.txt