# kubectl create secret generic mysecret --from-file=username.txt --from-file=password.txt

apiVersion: v1
kind: Pod
metadata:
  name: myvolconfig
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/bash","-c","sleep 1500"]
      volumeMounts:
        - name: testsecret
	  mountpath: /tmp/mysecret
  volumes:
    - name: testsecret # this should map with the name which we ccreated below
      secret:
        secretName: mysecret